kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wallaroo
nodes:
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels:  "wallaroo.ai/node-purpose=pipelines"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels:  "wallaroo.ai/node-purpose=persistent"      
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels:  "wallaroo.ai/node-purpose=persistent"
  extraPortMappings:     
  - containerPort: 30525
    hostPort: 8443
    protocol: TCP 