kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wallaroo
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings: 
  - containerPort: 30527
    hostPort: 8081
    protocol: TCP  
  - containerPort: 30526
    hostPort: 8080
    protocol: TCP     
  - containerPort: 30525
    hostPort: 8443
    protocol: TCP 